### ISSUE TITLE
关于api_key传入一些问题

### ISSUE THREAD

**Issue by Tender-sun** [ai4co/LLM-as-HH#8]
1、想请问这个项目api_key具体如何传入，试过很多方式始终无法顺利运行

2、关于适配api问题，能否像eoh一样支持传入endpoint(baseurl)，方便使用一些非openai官方的key

希望版主有空能够解答疑惑，十分感谢。

**Comment by henry-yeh** [comment]
感谢兴趣！

可以修改这里的代码：https://github.com/ai4co/LLM-as-HH/blob/5fa30b9da3ecb80b8a658352d26df08893f88a6c/utils/utils.py#L9-L27

例如，如果使用gpt系列，并使用openai api，对第14行进行修改如下：
`client = OpenAI(api_key=YOUR_OPENAI_API_KEY)`

可以参考这里对base_url进行修改，使用非openai官方的key：
https://github.com/ai4co/LLM-as-HH/blob/4cea10a53d94beb2c52d459fec4846894e5db809/utils/utils.py#L21-L28

**Comment by Tender-sun** [comment]
感谢答疑！
